trigger:
- main  # Automatically trigger the pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu agent

steps:
- task: UsePythonVersion@1
  inputs:
    versionSpec: '3.12'  # Specify the required Python version
    addToPath: true

- script: |
    echo "Installing dependencies..."
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python dependencies'

- script: |
    echo "Running Streamlit app for testing..."
    streamlit run app.py --server.headless true
  displayName: 'Run Streamlit App (Headless)'

- script: |
    echo "Pipeline execution completed successfully!"
  displayName: 'Finish Pipeline'
