trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Dependencies'

  - script: |
      zip -r app.zip .
    displayName: 'Archive App'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'azure-st'
      appName: 'psgds-cvg0e3c5f5geahcy'
      package: $(System.DefaultWorkingDirectory)/app.zip
